### ISSUE TITLE
Bot fails to create jira ticket when Issue/Priority are not selected

### ISSUE THREAD

**Issue by LanceSandino** [echoboomer/incident-bot#282]
When you click on `Create a Jira Ticket` the modal seems to default to `Task` as the `Issue Type` and `low` as the `Priority` (as seen in the image) but it doesn't actually default.

<img width="530" alt="image" src="https://github.com/echoboomer/incident-bot/assets/1300195/7d95bef1-3c6d-451a-935d-5507715a68e3">

If you do not select an `Issue Type` *and* `Priority` you get the following error:

```
incident-bot 07-13 18:14:45 ERROR:slack_bolt.App:Error: 'NoneType' object has no attribute 'get'
incident-bot 07-13 18:14:45 Traceback (most recent call last):
incident-bot 07-13 18:14:45   File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
incident-bot 07-13 18:14:45     listener.run_ack_function(request=request, response=response)
incident-bot 07-13 18:14:45   File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
incident-bot 07-13 18:14:45     return self.ack_function(
incident-bot 07-13 18:14:45            ^^^^^^^^^^^^^^^^^^
incident-bot 07-13 18:14:45   File "/incident-bot/bot/slack/modals.py", line 1700, in handle_submission
incident-bot 07-13 18:14:45     parsed = parse_modal_values(body)
incident-bot 07-13 18:14:45              ^^^^^^^^^^^^^^^^^^^^^^^^
incident-bot 07-13 18:14:45   File "/incident-bot/bot/templates/tools.py", line 24, in parse_modal_values
incident-bot 07-13 18:14:45     result[title] = content.get("selected_option").get("value")
incident-bot 07-13 18:14:45                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
incident-bot 07-13 18:14:45 AttributeError: 'NoneType' object has no attribute 'get'
incident-bot 07-13 18:14:48 WARNING:slack_bolt.App:handle_submission didn't call ack()
incident-bot 07-13 18:14:48 WARNING:slack_bolt.App:Unhandled request ({'type': 'view_submission', 'view': {'type': 'modal', 'callback_id': 'open_incident_create_jira_issue_modal'}})
incident-bot 07-13 18:14:48 ---
incident-bot 07-13 18:14:48 [Suggestion] You can handle this type of event with the following listener function:
incident-bot 07-13 18:14:48
incident-bot 07-13 18:14:48 @app.view("open_incident_create_jira_issue_modal")
incident-bot 07-13 18:14:48 def handle_view_submission_events(ack, body, logger):
incident-bot 07-13 18:14:48     ack()
incident-bot 07-13 18:14:48     logger.info(body)
incident-bot 07-13 18:14:48
```

**Comment by echoboomer** [comment]
Fixed by https://github.com/echoboomer/incident-bot/pull/283
