### ISSUE TITLE
Jira ticket issue types are not limited with selected project

### ISSUE THREAD

**Issue by kurawes** [echoboomer/incident-bot#344]
As of the latest update (ver 1.4.25) when creating a new jira ticket, the dynamically fetched Issue types are not restricted with the selected project, but are gathered from all the Jira projects. Meaning issue types are repeated as well if they are the same. Luckily it doesn't matter which one you choose, the ticket gets created, but if you choose an Issue type that does not exist in the given project, you get an error: Hmmm.. that didn't work. Check my logs for more information.

![image](https://github.com/echoboomer/incident-bot/assets/76185895/27c94374-86f0-4e9d-8951-ce32a0ed6dd4)
![image](https://github.com/echoboomer/incident-bot/assets/76185895/360fcd03-d233-409e-a278-0b25bbfb9828)

**Comment by LanceSandino** [comment]
@echoboomer 

yeah It doesn't even work for me

```
incident-bot 10-04 12:44:46 ERROR:slack_bolt.App:Error: The request to the Slack API failed. (url: https://www.slack.com/api/views.open)
incident-bot 10-04 12:44:46 The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] no more than 100 items allowed [json-pointer:/view/blocks/5/accessory/options]']}}
incident-bot 10-04 12:44:46 Traceback (most recent call last):
incident-bot 10-04 12:44:46   File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
incident-bot 10-04 12:44:46     listener.run_ack_function(request=request, response=response)
incident-bot 10-04 12:44:46   File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
incident-bot 10-04 12:44:46     return self.ack_function(
incident-bot 10-04 12:44:46            ^^^^^^^^^^^^^^^^^^
incident-bot 10-04 12:44:46   File "/incident-bot/bot/slack/modals.py", line 1659, in open_modal
incident-bot 10-04 12:44:46     client.views_open(
incident-bot 10-04 12:44:46   File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/client.py", line 4498, in views_open
incident-bot 10-04 12:44:46     return self.api_call("views.open", json=kwargs)
incident-bot 10-04 12:44:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
incident-bot 10-04 12:44:46   File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
incident-bot 10-04 12:44:46     return self._sync_send(api_url=api_url, req_args=req_args)
incident-bot 10-04 12:44:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
incident-bot 10-04 12:44:46   File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
incident-bot 10-04 12:44:46     return self._urllib_api_call(
incident-bot 10-04 12:44:46            ^^^^^^^^^^^^^^^^^^^^^^
incident-bot 10-04 12:44:46   File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 317, in _urllib_api_call
incident-bot 10-04 12:44:46     ).validate()
incident-bot 10-04 12:44:46       ^^^^^^^^^^
incident-bot 10-04 12:44:46   File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
incident-bot 10-04 12:44:46     raise e.SlackApiError(message=msg, response=self)
incident-bot 10-04 12:44:46 slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/views.open)
incident-bot 10-04 12:44:46 The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] no more than 100 items allowed [json-pointer:/view/blocks/5/accessory/options]']}}
```

**Comment by echoboomer** [comment]
Thanks for reporting this. Once again, testing in a small test environment does me more harm than good. Will look at this.

**Comment by echoboomer** [comment]
@kurawes Just released version `v1.4.26` with a corresponding Helm chart release that resolves this issue. Priority types will only come from the project supplied the config. For Lance's case, this was simply a matter of there being too many objects in the block for the modal. If there really are that many issue types returned for a single project, there may not be a better way to do this in said cases, but I'll work on implementing some testing logic in the app to verify how many blocks will actually be created.

**Comment by LanceSandino** [comment]
```incident-bot 10-04 17:59:59 WARNING:slack_bolt.App:open_modal didn't call ack()
incident-bot 10-04 17:59:59 WARNING:slack_bolt.App:Unhandled request ({'type': 'block_actions', 'block_id': 'help_buttons', 'action_id': 'open_incident_create_jira_issue_modal'})
incident-bot 10-04 17:59:59 ---
incident-bot 10-04 17:59:59 [Suggestion] You can handle this type of event with the following listener function:
incident-bot 10-04 17:59:59
incident-bot 10-04 17:59:59 @app.action("open_incident_create_jira_issue_modal")
incident-bot 10-04 17:59:59 def handle_some_action(ack, body, logger):
incident-bot 10-04 17:59:59     ack()
incident-bot 10-04 17:59:59     logger.info(body)
incident-bot 10-04 17:59:59
incident-bot 10-04 18:00:15 ERROR:slack_bolt.App:Error: list index out of range
incident-bot 10-04 18:00:15 Traceback (most recent call last):
incident-bot 10-04 18:00:15   File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
incident-bot 10-04 18:00:15     listener.run_ack_function(request=request, response=response)
incident-bot 10-04 18:00:15   File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
incident-bot 10-04 18:00:15     return self.ack_function(
incident-bot 10-04 18:00:15            ^^^^^^^^^^^^^^^^^^
incident-bot 10-04 18:00:15   File "/incident-bot/bot/slack/modals.py", line 1601, in open_modal
incident-bot 10-04 18:00:15     "text": issue_types[-1],
incident-bot 10-04 18:00:15             ~~~~~~~~~~~^^^^
incident-bot 10-04 18:00:15 IndexError: list index out of range
```

**Comment by LanceSandino** [comment]
Our jira is probably _huge_ 
IMO it would be cool to dynamically pull them _and/or_ allow configuration for them 🤷🏽‍♂️

**Comment by echoboomer** [comment]
@LanceSandino that error looks like it couldn't get a list of issue types for whatever project you're using for incident management, but I know that's likely not the issue. Setting manually may be a good option, but we'd still have to verify that type exists before making a ticket.

**Comment by kurawes** [comment]
Unfortunately the new version (1.4.26) breaks the jira ticket creation completely. It doesn't even open the window anymore to start creating a ticket. Only thing that changes is it adds a little emoticon to the right of the buttons.

![erroremoticon](https://github.com/echoboomer/incident-bot/assets/76185895/44af56d1-42d7-431d-b441-bb786efd01ab)

And the logs show:

```
DEBUG:atlassian.rest_client:curl --silent -X GET -H 'Content-Type: application/json' -H 'Accept: application/json'  'https://team-xxxxxxxx.atlassian.net/rest/api/2/project/SUPPORT'
WARNING:slack_bolt.App:open_modal didn't call ack()
WARNING:slack_bolt.App:Unhandled request ({'type': 'block_actions', 'block_id': 'help_buttons', 'action_id': 'open_incident_create_jira_issue_modal'})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.action("open_incident_create_jira_issue_modal")
def handle_some_action(ack, body, logger):
    ack()
    logger.info(body)
``` 

And another part: 

```
ERROR:slack_bolt.App:Error: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/usr/local/lib/python3.11/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
           ^^^^^^^^^^^^^^^^^^
  File "/incident-bot/bot/slack/modals.py", line 1601, in open_modal
    "text": issue_types[-1],
            ~~~~~~~~~~~^^^^
IndexError: list index out of range
``` 

And it also creates a lot of these GET requests that detail all the incident types and other info associated with them ... like close to a hundred:

```
DEBUG:atlassian.rest_client:HTTP: GET rest/api/2/project/SUPPORT -> 200 OK
DEBUG:atlassian.rest_client:HTTP: Response text -> {"expand":"description,lead,issueTypes,url,projectKeys,permissions,insight","self":"https://team-xxxxxxxx.atlassian.net/rest/api/2/project/10019" ....
```

**Comment by echoboomer** [comment]
@LanceSandino @kurawes `v1.4.27` is out now with the option to set issue types manually in the config yaml file. If not provided it will attempt to get them automatically. I'd recommend using this approach if you have this error again.

**Comment by kurawes** [comment]
@echoboomer thank you for the fix, new version seems to work nicely with manually configured issue types and priorities (thou these are never asked when making a jira ticket)

**Comment by LanceSandino** [comment]
When I only leave `Epic` it doesn't show any `priorities`

Also any chance in the future we could pull other fields?

**Comment by echoboomer** [comment]
@kurawes submitting the request to create the ticket with priority associated was causing errors so I redacted it for now. Will look into why.

@LanceSandino any examples of other fields?
